version: '3'
services:
  nodejs-server:
    container_name: backend_nodejs
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
    depends_on:
      - "mysql"
    networks:
      - CoinManager
  reactjs:
    container_name: frontend_reactjs
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
    networks:
      - CoinManager
    depends_on:
      - "nodejs-server"
  mysql:
    container_name: database_mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: CoinManager
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root 
    volumes:
        - ./database:/docker-entrypoint-initdb.d
        # - ./conf:/etc/mysql/conf.d
        # - persistent:/var/lib/mysql
    networks:
        - CoinManager
volumes:
    persistent:
networks:
  CoinManager:
    driver: bridge